= Drivers & Language Guides
:level: Intermediate
:page-level: Intermediate
:author: Jennifer Reif
:category: drivers
:tags: programming-languages, applications, bolt, app-development
:page-ad-overline-link: https://neo4j.com/cloud/aura/?ref=developer-guides
:page-ad-overline: Neo4j Aura
:page-ad-title: Don't Have a Neo4j Instance? Launch one now.
:page-ad-description: Free forever, no credit card required.
:page-ad-link: https://neo4j.com/cloud/aura/?ref=developer-guides
:page-ad-underline-role: button
:page-ad-underline: Start on AuraDB
:page-deprecated-title: the Getting Started Manual
:page-deprecated-redirect: https://neo4j.com/docs/getting-started/current/languages-guides/

// This page has been deprecated in favour of the Getting Started Guide, maintained by the Neo4j Documentation team. This page will be removed and redirected in the future.

[#neo4j-app-dev]
== Neo4j Language Guides
These guides and tutorials are designed to provide detailed examples of how to integrate Neo4j with your preferred programming language.
Neo4j *officially supports the drivers for .Net, Java, JavaScript, Go, and Python* for the binary Bolt protocol.
Our community contributors provide drivers for all major programming languages for all protocols and APIs.
In this section, we provide an introduction and a consistent example application for several languages and Neo4j drivers.



[#graphacademy]
== Learn with GraphAcademy

We have a range of link:https://graphacademy.neo4j.com/categories/developer/?ref=guides[Neo4j Developer courses^] that teach you to build connect to Neo4j using each of our officially supported Drivers.

link:https://graphacademy.neo4j.com/courses/app-java/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-java/badge/[Building Neo4j Applications with Java, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-nodejs/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-nodejs/badge/[Building Neo4j Applications with Node.js, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-python/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-python/badge/[Building Neo4j Applications with Python, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-dotnet/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-dotnet/badge/[Building Neo4j Applications with .NET, width=120]^]
link:https://graphacademy.neo4j.com/courses/app-go/?ref=guides[image:https://graphacademy.neo4j.com/courses/app-go/badge/[Building Neo4j Applications with Go, width=120]^]



[#connect-neo4j]
== How to connect to Neo4j?

If you've created an link:{aura_signup}[AuraDB instance^], or link:/download/[installed] and started Neo4j as a server on your system,
you can already work interactively with the database via the built-in Neo4j Browser, which you will find in the AuraDB console, or if you're running locally, on http://localhost:7474[localhost:7474].

To build an application, you want to connect to Neo4j from your technology stack.
Fortunately it is very easy using a driver which connects to Neo4j via Bolt or Http.


[#bolt-protocol]
== The binary Bolt Protocol

Starting with Neo4j 3.0 we support a binary protocol called Bolt.
It is based on the PackStream serialization and supports the Cypher type system, protocol versioning, authentication and TLS via certificates.
For Neo4j Clusters, Bolt provides smart client routing with load balancing and failover.

The binary protocol is enabled in Neo4j by default, so you can use any language driver that supports it.

Neo4j officially provides drivers for link:/developer/dotnet/[.NET], link:/developer/java/[Java], link:/developer/spring-data-neo4j/[Spring], link:/developer/javascript/[JavaScript], link:/developer/go/[Go], and link:/developer/python/[Python].

// You can find detailed information about the official drivers in the {drivermanual}[Neo4j Driver Manual^].

_For more details on the protocol implementation, see the https://github.com/neo4j-contrib/boltkit[implementers documentation^]._

[#neo4j-drivers]
== All Neo4j Drivers

Thanks to the Neo4j contributor community, there are additionally drivers for almost every popular programming language,
most of which mimic existing database driver idioms and approaches.
Get started with your stack now, see the dedicated page for more detail.

[cols="5*",width=100]
|===
| link:/developer/java/[icon:check-circle-o[] Java]
| link:/developer/spring-data-neo4j/[icon:check-circle-o[] Spring]
| link:/developer/neo4j-ogm/[icon:check-circle-o[] Neo4j-OGM]
| link:/developer/dotnet/[icon:check-circle-o[] .NET]
| link:/developer/javascript/[icon:check-circle-o[] JavaScript]
| link:/developer/python/[icon:check-circle-o[] Python]
| link:/developer/go/[icon:check-circle-o[] Go]
| link:/developer/ruby/[Ruby]
| link:/developer/php/[PHP]
| link:/developer/erlang-elixir/[Erlang/Elixir]
| link:/developer/perl/[Perl]
| link:/developer/c/[C/C++]
| link:/developer/clojure/[Clojure]
| link:/developer/haskell/[Haskell]
| link:/developer/r/[R]
|===

If you are new to development, we recommend the https://www.jetbrains.com/products.html[Jetbrains IDE^] for a good developer experience, which also comes with a link:/blog/jetbrains-ide-plugin-graph-database/[Neo4j Database plugin^].

include::example-project.adoc[tags=intro-app-project,lines=21..35]

link:/developer/example-project/[Read More^]

[#http-api]
== Using the HTTP API

[NOTE]
--
The HTTP API is available in Community Edition and Enterprise Edition, but not in AuraDB
--

If you want to access Neo4j programmatically, you can also use the HTTP-API, which allow you to:

* POST one or more Cypher statements with parameters
* Keep transactions open over multiple requests
* Choose different result formats

Let's look at one of the underlying remote API endpoint that Neo4j offers to execute queries.
These APIs can be then used directly via a HTTP library or a driver for your language.

A simple HTTP Cypher request, executable in the Neo4j Browser would look like this:

[source, json]
----
:POST /db/data/transaction/commit {"statements":[
      {"statement":"CREATE (p:Person {firstName: $name}) RETURN p",
       "parameters":{"name":"Daniel"}}
    ]}
----

Some of the language drivers use the HTTP API under the hood, but make them available in a more convenient way.

[.ad]
== link:https://graphacademy.neo4j.com/[Learn with GraphAcademy^]

Learn everything you need to know to build an application on top of Neo4j with free, hands-on courses from link:https://graphacademy.neo4j.com/[Neo4j GraphAcademy^].

link:https://graphacademy.neo4j.com/?ref=guides[Learn more^,role=button]
link:https://graphacademy.neo4j.com/categories/?ref=guides[or view courses by category^]
