


The Neo4j .NET driver is *officially supported* by Neo4j and connects to the database using the binary protocol.
It aims to be minimal, while being idiomatic to .NET.

Please note that the following example makes use of the `Neo4j.Driver.Simple` package that implements a blocking interface
around the 'main' driver.
This is to aid in clarity and simplicity for those just starting out with the Neo4j .Net driver.

[source, subs=attributes]
----
PM> Install-Package Neo4j.Driver.Simple-{dotnet-driver-version}
----

For real projects, the `Neo4j.Driver` package should be used instead.

[source, subs=attributes]
----
PM> Install-Package Neo4j.Driver-{dotnet-driver-version}
----

// TODO: Add this include back in
[source, c]
----
include::https://raw.githubusercontent.com/neo4j/neo4j-dotnet-driver/{dotnet-driver-version}/Neo4j.Driver/Neo4j.Driver.Tests.Integration/Examples.cs[tag=hello-world,indent=0]
----


include::./driver-warning.adoc[]

[cols="3*"]
|===
| Name
| icon:tag[] Version
| icon:user[] Authors

| Neo4jDotNetDriver
| {dotnet-driver-version}
| The Neo4j Team, http://twitter.com/cskardon[Charlotte Skardon], https://twitter.com/IngvarKofoed[Martin Jensen]

| http://www.nuget.org/packages/Neo4j.Driver[icon:gift[] NuGet Package]
| {examples}/movies-dotnet-bolt[icon:play-circle[] .NET Example], {examples}/movies-dotnetcore-bolt[icon:play-circle[] .NET core example]
| https://community.neo4j.com/c/drivers-stacks/NET[Neo4j Online Community^]

| {drivermanual}[icon:book[] Docs^]
| link:/docs/api/dotnet-driver/current/[icon:code[] API]
| http://github.com/neo4j/neo4j-dotnet-driver[icon:github[] Source]
|===
