= Neo4j Developer Guides

image::https://github.com/neo4j-documentation/developer-guides/workflows/Trigger%20Publish/badge.svg[Trigger Publish]
image::https://github.com/neo4j-documentation/docs-refresh/workflows/Publish%20Developer/badge.svg[Publish Developer]

Built with link:https://antora.org/[Antora^].

- link:https://docs.antora.org/antora/latest/install/install-antora/[Install Antora]
- link:https://docs.antora.org/antora/2.3/standard-directories/[Standard File and Directory Set^]
- link:https://docs.antora.org/antora/2.3/module-directories/[Module Directories and Modules^]

== Installation

To build these docs locally you will need link:https://nodejs.org/en/download/package-manager/[Node & NPM^] installed.

To install the dependencies run:

[source,sh]
npm install


== Live Preview

To preview the docs, run:

[source,sh]
npm run dev


This will build a set of HTML files in `build/site` and then serve them through an express server at http://localhost:8000.
The dev script will also listen for changes and automatically rebuild the files automatically.
You'll still need to refresh the page to view the changes.


== Publishing

Pushing to the `publish` branch of this repo will trigger a rebuild of the HTML and CSS files in the link:https://github.com/neo4j-documentation/docs-refresh[Docs Refresh^] repo using a Github Action.


[source,sh]
----
# clone the repo
git clone https://github.com/neo4j-documentation/developer-guides
# stage the commit
touch modules/ROOT/page.adoc
git add .
# Commit
git commit -m "My changes"
# Optionally, do a pull to make sure you have the latest.
git pull
# Merge the latest changes on the remote branch
git push origin master
# Push the HEAD of the branch to the publish branch
git push origin HEAD:publish
----

At the end of the build process, the files are uploaded to the `static-content.neo4j.com` S3 Bucket.  From there, they are synced up to the Neo4j.com server once an hour, on the hour by a cronjob.

